### ISSUE TITLE
夜莺监控 用户管理 前端页面排版样式不合理

### ISSUE THREAD

**Issue by shier-1212** [n9e/vuedemo#1]
![jietu截图](https://user-images.githubusercontent.com/73478963/109446039-dea73c00-7a7b-11eb-8477-b4aae1ae325b.jpg)

**Comment by jsers** [comment]
@shier-1212 
麻烦提供下目前用的前端版本是？
可以看下 pub/rdb/manifest.json 里面有个 v 字段（如果不存在这个字段意味着你当前使用的前端版本太低了）

**Comment by UlricQin** [comment]
另外这个截图截全一点？现在看起来每列内容都不是很宽，是不是下面有某一列内容比较宽导致的

**Comment by shier-1212** [comment]
-我这边整个界面都是这样的。


---- 原始邮件 -----发件人：UlricQin <notifications@github.com>
收件人：n9e/vuedemo <vuedemo@noreply.github.com>
抄送人：shier-1212 <84zhy@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[n9e/vuedemo]_夜莺监控_用户管理_前端页面排版样式不合理_(#1)
日期：2021年03月02日 10点48分



另外这个截图截全一点？现在看起来每列内容都不是很宽，是不是下面有某一列内容比较宽导致的

**Comment by shier-1212** [comment]
这个是manifest.json   文件的内容   单独的V字段好像是没有
----- 原始邮件 -----发件人：jsers <notifications@github.com>
收件人：n9e/vuedemo <vuedemo@noreply.github.com>
抄送人：shier-1212 <84zhy@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[n9e/vuedemo]_夜莺监控_用户管理_前端页面排版样式不合理_(#1)
日期：2021年03月02日 10点47分



@shier-1212


麻烦提供下目前用的前端版本是？


可以看下 pub/rdb/manifest.json 里面有个 v 字段（如果不存在这个字段意味着你当前使用的前端版本太低了）

**Comment by jsers** [comment]
升级下前端，你当前用的版本比较老，后面已经优化过这个表格

shier-1212 <notifications@github.com> 于2021年3月2日周二 下午12:46写道：

**Comment by shier-1212** [comment]
请问要升级到哪个版本。



发自我的iPhone

**Comment by jsers** [comment]
建议升级到最新版本，具体可以看下 nightingale 的 release

shier-1212 <notifications@github.com> 于2021年3月3日周三 下午1:47写道：

**Comment by shier-1212** [comment]
谢谢！3.7的版本应该可以。
